name: Deploy VirtusCorp Test

on:
  push:
    branches:
      - main  # Деплой запускается при пуше в main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t virtuscorp_tst ./virtuscorp_tst
          docker tag virtuscorp_tst ${{ secrets.DOCKER_USERNAME }}/virtuscorp_tst:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/virtuscorp_tst:latest

  deploy:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy on Server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e  # Прерываем выполнение при ошибках
            docker login -u "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
            cd /home/deploy/www
            docker-compose pull
            docker-compose up -d --no-deps --build virtuscorp_tst
            docker system prune -af
          EOF
